### ISSUE TITLE
Request: Packaging psychopy_tobii_infant with PyHab?

### ISSUE THREAD

**Issue by jfkominsky** [yh-luo/psychopy_tobii_infant#19]
Hi Yu-Han, I'm the creator of PyHab (Kominsky, 2019; https://github.com/jfkominsky/PyHab), and I was thinking about adding psychopy_tobii_infant to PyHab to make it easier for people to build eye-tracking experiments. You've done a really great job with it, and it's easy for PyHab to interface with it. I was thinking of literally just taking the module folder and adding it as a sub-folder within PyHab, giving you full credit for it of course! 

Let me know if you're ok with that or have any questions.

Kominsky, J. F. (2019). PyHab: Open-source real time infant gaze coding and stimulus presentation software. Infant Behavior and Development, 54, 114-119. https://doi.org/10.1016/j.infbeh.2018.11.006

**Comment by yh-luo** [comment]
Hi,
Please do that :)
It's my honor that `psychopy_tobii_infant` is helpful for others!

The only concern I have is that the package is not actively maintained, since I'm no longer working in academics and have no access to a Tobii eye tracker.
Would you be interested in maintaining the package? Though I _think_ it's working as expected mostly.
No pressure of course, you can simply fork and integrate it with PyHab.

On a side note, `components` branch is my early attempt to create Builder components for PsychoPy. May be helpful if you need a GUI for `psychopy_tobii_infant`.

p.s., I've known PyHab when I was in graduate school, though I eventually used an eye tracker for my experiments. I'm beyond delighted for the request!

**Comment by jfkominsky** [comment]
Thank you! For right now I will simply take a copy of it as-is, since it works. If it needs updating in the future I will do what I can on both the PyHab end and for the package itself.

PyHab uses its own builder interface separate from the PsychoPy one, and the integration is going to be pretty simplistic at least to start, but thanks for highlighting the components branch, if I start incorporating PyHab into the main PsychoPy builder it will be a big help!
